ALTER TABLE `vivazul_rfb`.`empresa`   
  CHANGE `cnpj_basico` `cnpj_basico` CHAR(8) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `razao_social` `razao_social` VARCHAR(255) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `natureza_juridica` `natureza_juridica` VARCHAR(10) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `qualificacao_responsavel` `qualificacao_responsavel` VARCHAR(10) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `porte_empresa` `porte_empresa` VARCHAR(100) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `ente_federativo_responsavel` `ente_federativo_responsavel` CHAR(14) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL;


ALTER TABLE `vivazul_rfb`.`estabelecimento`   
  CHANGE `cnpj_basico` `cnpj_basico` CHAR(8) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `cnpj_ordem` `cnpj_ordem` CHAR(4) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `cnpj_dv` `cnpj_dv` CHAR(2) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `identificador_matriz_filial` `identificador_matriz_filial` CHAR(1) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `nome_fantasia` `nome_fantasia` VARCHAR(255) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `situacao_cadastral` `situacao_cadastral` CHAR(2) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `data_situacao_cadastral` `data_situacao_cadastral` CHAR(10) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `motivo_situacao_cadastral` `motivo_situacao_cadastral` CHAR(2) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `nome_cidade_exterior` `nome_cidade_exterior` VARCHAR(255) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `pais` `pais` CHAR(10) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `data_inicio_atividade` `data_inicio_atividade` CHAR(10) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `cnae_fiscal_principal` `cnae_fiscal_principal` CHAR(7) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `cnae_fiscal_secundaria` `cnae_fiscal_secundaria` VARCHAR(255) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `tipo_logradouro` `tipo_logradouro` VARCHAR(255) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `logradouro` `logradouro` VARCHAR(255) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `numero` `numero` VARCHAR(255) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `complemento` `complemento` VARCHAR(255) NULL,
  CHANGE `bairro` `bairro` VARCHAR(255) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `cep` `cep` CHAR(10) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `uf` `uf` CHAR(2) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `municipio` `municipio` VARCHAR(5) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `ddd_1` `ddd_1` VARCHAR(2) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `telefone_1` `telefone_1` VARCHAR(9) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `ddd_2` `ddd_2` VARCHAR(2) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `telefone_2` `telefone_2` VARCHAR(9) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `ddd_fax` `ddd_fax` VARCHAR(2) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `fax` `fax` VARCHAR(9) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `correio_eletronico` `correio_eletronico` VARCHAR(255) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `situacao_especial` `situacao_especial` VARCHAR(255) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  CHANGE `data_situacao_especial` `data_situacao_especial` VARCHAR(10) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL;
